# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cfa16b0c3cf666ba26ed8c048d03f495d9577201915e51b23476edf6706cd2c1acafc774be6c63e81a77f7ada4d81cabfc5111d9aefab5f2d277449a5d2b18f

test:
  secret_key_base: b19a3de2cfb341c249b16179a5a7a0e4fec7c042cc3034e6ffe68b330c861d548b5e56a090a69e19906eebe8f954a0846d1815dc6e786560da43ce18ef73f835

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
